@baseUrl = COLOCAR O SEU LINK

###
GET {{baseUrl}}/categorias

###
GET {{baseUrl}}/categorias/1

###
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Sobremesas"
}

###
PUT {{baseUrl}}/categorias/1
Content-Type: application/json

{
    "nome": "Pratos Principais"
}

###
DELETE {{baseUrl}}/categorias/1
